variables:
#  MY_URLS: "https://phpmyadmin.local" #"https://flask-app.local" 
   FLASK_ENDPOINT: https://flask-app.local
   PHP_ENDPOINT: https://phpmyadmin.local

stages:
  - deploy_docker
deploy_docker:
  tags:
    - shell
  stage: deploy_docker
  before_script:
#  to enable the pull of the private flask image from hub
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
  script:
#    - docker network create proxy
    - docker-compose -f db.yml -f flask-php.yml -f proxy.yml down --remove-orphans
    - chmod +x wait.sh
    - ./wait.sh
    - docker-compose -f db.yml up -d
    - ./wait.sh
    - docker-compose -f flask-php.yml -f proxy.yml up -d

  environment:
    name: docker-compose
    url: $FLASK_ENDPOINT
#      flask-app: $FLASK_ENDPOINT
#      phpmyadmin: $PHP_ENDPOINT
