version: '2.29.1'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # env_file:
    #   - ./php.env
    environment:
    - VIRTUAL_HOST=phpmyadmin.local
    - VIRTUAL_PORT=80
    - PMA_HOST=db
    - PMA_PORT=3306 
    - VIRTUAL_PATH=/
    - HTTPS_METHOD=noredirect
    - CERT_NAME=phpmyadmin.local
    - PMA_HOST=db
    - PMA_USER=ze
    - PMA_PASSWORD=deeb
    - PMA_PORT=3306
    ports:
      - "8082:80"

    networks:
      - proxy

  flask-app:
    image: amrkedra/flask-image:v1
    # env_file:
    #   - ./flask.env 
    environment:
    - VIRTUAL_HOST=python.local
    - VIRTUAL_PORT=5000
    - VIRTUAL_PATH=/
    - HTTPS_METHOD=noredirect
    - CERT_NAME=python.local
    - MYSQL_HOST=db
    - MYSQL_USER=ze
    - MYSQL_PASSWORD=deeb
    - MYSQL_DBNAME=mydb
    ports:
      - "8080:5000"
      - "5000:5000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Adjust as needed
    networks:
      - proxy

networks:
  proxy:
    external: true
    driver: bridge
